[2024-12-11T13:54:53.639+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-11T13:54:53.651+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_etl_dag.load_to_mariadb manual__2024-12-11T13:54:50.841290+00:00 [queued]>
[2024-12-11T13:54:53.657+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_etl_dag.load_to_mariadb manual__2024-12-11T13:54:50.841290+00:00 [queued]>
[2024-12-11T13:54:53.658+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-12-11T13:54:53.666+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): load_to_mariadb> on 2024-12-11 13:54:50.841290+00:00
[2024-12-11T13:54:53.673+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'first_etl_dag', 'load_to_mariadb', 'manual__2024-12-11T13:54:50.841290+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmp2ebf9i61']
[2024-12-11T13:54:53.674+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask load_to_mariadb
[2024-12-11T13:54:53.676+0000] {logging_mixin.py:190} WARNING - /opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-11T13:54:53.677+0000] {standard_task_runner.py:72} INFO - Started process 235 to run task
[2024-12-11T13:54:53.712+0000] {task_command.py:467} INFO - Running <TaskInstance: first_etl_dag.load_to_mariadb manual__2024-12-11T13:54:50.841290+00:00 [running]> on host 9e626d86f839
[2024-12-11T13:54:53.764+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='first_etl_dag' AIRFLOW_CTX_TASK_ID='load_to_mariadb' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T13:54:50.841290+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-11T13:54:50.841290+00:00'
[2024-12-11T13:54:53.766+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-11T13:54:53.766+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-11T13:54:53.767+0000] {logging_mixin.py:190} INFO - Current task name:load_to_mariadb state:running start_date:2024-12-11 13:54:53.652506+00:00
[2024-12-11T13:54:53.767+0000] {logging_mixin.py:190} INFO - Dag name:first_etl_dag and current dag run status:running
[2024-12-11T13:54:53.768+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-11T13:54:53.769+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-11T13:54:53.770+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/bitnami/airflow/dags/scripts/load_to_mariadb.py']
[2024-12-11T13:54:53.776+0000] {subprocess.py:86} INFO - Output:
[2024-12-11T13:54:53.790+0000] {subprocess.py:93} INFO - python: can't open file '/opt/bitnami/airflow/dags/scripts/load_to_mariadb.py': [Errno 2] No such file or directory
[2024-12-11T13:54:53.792+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-12-11T13:54:53.800+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-11T13:54:53.804+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-11T13:54:53.805+0000] {logging_mixin.py:190} INFO - Task start:2024-12-11 13:54:53.652506+00:00 end:2024-12-11 13:54:53.804595+00:00 duration:0.152089
[2024-12-11T13:54:53.806+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): load_to_mariadb> dag:<DAG: first_etl_dag> dagrun:<DagRun first_etl_dag @ 2024-12-11 13:54:50.841290+00:00: manual__2024-12-11T13:54:50.841290+00:00, state:running, queued_at: 2024-12-11 13:54:50.853606+00:00. externally triggered: True>
[2024-12-11T13:54:53.806+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2024-12-11T13:54:53.807+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=first_etl_dag, task_id=load_to_mariadb, run_id=manual__2024-12-11T13:54:50.841290+00:00, execution_date=20241211T135450, start_date=20241211T135453, end_date=20241211T135453
[2024-12-11T13:54:53.817+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-11T13:54:53.818+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2 for task load_to_mariadb (Bash command failed. The command returned a non-zero exit code 2.; 235)
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-11T13:54:53.852+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-11T13:54:53.868+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-11T13:54:53.871+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
